name: PS2Bot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.HOST_PORT }}
          command: cd ${{ secrets.dir }} && git pull origin master 
                   && docker build -t ps2bot:1.3 . --force-rm=true --no-cache 
                   && docker ps -a | grep 'ps2bot'| awk 'END{if(NR>=1){print $1}}' | xargs -r docker rm -f  
                   && docker run -d -it --env  token=${{ secrets.token }} --name ps2bot ps2bot:1.3
