name: PS2Bot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh proxy command
        uses: appleboy/ssh-action@0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          proxy-host: ${{ secrets.PROXY_HOST }}
          proxy-username: ${{  secrets.PROXY_USERNAME}}
          proxy-port: ${{  secrets.PROXY_PORT  }}
          proxy-key: ${{  secrets.PROXY_KEY }}
          script: cd ${{ secrets.dir }} && git pull origin master 
                   && docker build -t ps2bot:1.3 . --force-rm=true --no-cache 
                   && docker ps -a | grep 'ps2bot'| awk 'END{if(NR>=1){print $1}}' | xargs -r docker rm -f  
                   && docker run -d -it --restart=always --env  token=${{ secrets.token }} --name ps2bot ps2bot:1.3
