name: PS2Bot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command: cd ${{ secrets.dir }} && git pull origin master 
                   && docker build -t ps2bot:1.3 . --force-rm=true --no-cache 
                   && docker ps -a | grep 'ps2bot'| awk 'END{if(NR>=1){print $1}}' | xargs -r docker rm -f  
                   && docker run -d -it --log-driver=fluentd --log-opt fluentd-address=172.16.0.142:24224 --log-opt tag=docker.ps2bot --restart=always --env  token=${{ secrets.token }} --name ps2bot ps2bot:1.3
