name: PS2Bot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: export BOT_TOKEN= ${{secrets.token}} && cd /home/seigo/PS2Bot/ && git pull origin master && docker build -t ps2bot:1.3 . --force-rm=true --no-cache && docker stop ps2bot && docker rm ps2bot && docker run -d -it --env BOT_TOKEN --name ps2bot ps2bot:1.3
