name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    # - name: init
    #   env :
    #     SSH_KEY: ${{ secrets.SSH_KEY }}
    #     HOST_PORT: ${{ secrets.HOST_PORT }}
    #     HOST_USER: ${{ secrets.HOST_USER }}
    #     HOST_NAME: ${{ secrets.HOST_NAME }}
    #     TOKEN: ${{ secrets.token }}
      # run: |
      #   echo ${SSH_KEY} > id_rsa && chmod 600 id_rsa
      #   sed -i -e "s#\\\\n#\n#g" id_rsa
      #   ssh -i id_rsa  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${HOST_PORT} ${HOST_USER}@${HOST_NAME} 'export BOT_TOKEN=${TOKEN} && cd /home/seigo/PS2Bot/ && git pull origin master && docker build -t ps2bot:1.3 . --force-rm=true --no-cache && docker stop ps2bot && docker rm ps2bot && docker run -d -it --env BOT_TOKEN --name ps2bot ps2bot:1.3'
      - name: ssh
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USER }}
          privateKey: ${{ secrets.SSH_KEY1 }}
          port: ${{ secrets.HOST_PORT }}
          command: cd /home/seigo/PS2Bot/ && git pull origin master && docker build -t ps2bot:1.3 . --force-rm=true --no-cache && docker stop ps2bot && docker rm ps2bot && docker run -d -it --env ${{ secrets.token }} --name ps2bot ps2bot:1.3
